
namespace WMS
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.sidePanel = new System.Windows.Forms.Panel();
            this.BtnMasterCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnMasterPart = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnRackLocation = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnSetting = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnLogHistory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.BtnUser = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnBalance = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnStockOut = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnGenerate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnStockIn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnSystemOverview = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Parent_Panel = new System.Windows.Forms.Panel();
            this.LblTittle = new Bunifu.UI.WinForms.BunifuLabel();
            this.Main_Panel = new System.Windows.Forms.Panel();
            this.sidePanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.Parent_Panel.SuspendLayout();
            this.SuspendLayout();
            // 
            // sidePanel
            // 
            this.sidePanel.BackColor = System.Drawing.Color.SteelBlue;
            this.sidePanel.Controls.Add(this.BtnMasterCustomer);
            this.sidePanel.Controls.Add(this.BtnMasterPart);
            this.sidePanel.Controls.Add(this.BtnRackLocation);
            this.sidePanel.Controls.Add(this.BtnSetting);
            this.sidePanel.Controls.Add(this.BtnLogHistory);
            this.sidePanel.Controls.Add(this.pictureBox1);
            this.sidePanel.Controls.Add(this.BtnUser);
            this.sidePanel.Controls.Add(this.BtnBalance);
            this.sidePanel.Controls.Add(this.BtnStockOut);
            this.sidePanel.Controls.Add(this.BtnGenerate);
            this.sidePanel.Controls.Add(this.BtnStockIn);
            this.sidePanel.Controls.Add(this.BtnSystemOverview);
            this.sidePanel.Location = new System.Drawing.Point(12, 15);
            this.sidePanel.Name = "sidePanel";
            this.sidePanel.Size = new System.Drawing.Size(257, 722);
            this.sidePanel.TabIndex = 2;
            // 
            // BtnMasterCustomer
            // 
            this.BtnMasterCustomer.AllowAnimations = true;
            this.BtnMasterCustomer.AllowMouseEffects = true;
            this.BtnMasterCustomer.AllowToggling = true;
            this.BtnMasterCustomer.AnimationSpeed = 200;
            this.BtnMasterCustomer.AutoGenerateColors = false;
            this.BtnMasterCustomer.AutoRoundBorders = false;
            this.BtnMasterCustomer.AutoSizeLeftIcon = true;
            this.BtnMasterCustomer.AutoSizeRightIcon = true;
            this.BtnMasterCustomer.BackColor = System.Drawing.Color.Transparent;
            this.BtnMasterCustomer.BackColor1 = System.Drawing.Color.SteelBlue;
            this.BtnMasterCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnMasterCustomer.BackgroundImage")));
            this.BtnMasterCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnMasterCustomer.ButtonText = "Master Customer";
            this.BtnMasterCustomer.ButtonTextMarginLeft = 0;
            this.BtnMasterCustomer.ColorContrastOnClick = 45;
            this.BtnMasterCustomer.ColorContrastOnHover = 45;
            this.BtnMasterCustomer.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.BtnMasterCustomer.CustomizableEdges = borderEdges1;
            this.BtnMasterCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnMasterCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnMasterCustomer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnMasterCustomer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnMasterCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnMasterCustomer.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.BtnMasterCustomer.ForeColor = System.Drawing.Color.White;
            this.BtnMasterCustomer.IconLeft = global::WMS.Properties.Resources.client_59694081;
            this.BtnMasterCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnMasterCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnMasterCustomer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnMasterCustomer.IconMarginLeft = 11;
            this.BtnMasterCustomer.IconPadding = 10;
            this.BtnMasterCustomer.IconRight = null;
            this.BtnMasterCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnMasterCustomer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnMasterCustomer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnMasterCustomer.IconSize = 25;
            this.BtnMasterCustomer.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.BtnMasterCustomer.IdleBorderRadius = 1;
            this.BtnMasterCustomer.IdleBorderThickness = 1;
            this.BtnMasterCustomer.IdleFillColor = System.Drawing.Color.SteelBlue;
            this.BtnMasterCustomer.IdleIconLeftImage = global::WMS.Properties.Resources.client_59694081;
            this.BtnMasterCustomer.IdleIconRightImage = null;
            this.BtnMasterCustomer.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.BtnMasterCustomer.IndicateFocus = true;
            this.BtnMasterCustomer.Location = new System.Drawing.Point(0, 520);
            this.BtnMasterCustomer.Name = "BtnMasterCustomer";
            this.BtnMasterCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnMasterCustomer.OnDisabledState.BorderRadius = 1;
            this.BtnMasterCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnMasterCustomer.OnDisabledState.BorderThickness = 1;
            this.BtnMasterCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnMasterCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnMasterCustomer.OnDisabledState.IconLeftImage = null;
            this.BtnMasterCustomer.OnDisabledState.IconRightImage = null;
            this.BtnMasterCustomer.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnMasterCustomer.onHoverState.BorderRadius = 1;
            this.BtnMasterCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnMasterCustomer.onHoverState.BorderThickness = 1;
            this.BtnMasterCustomer.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnMasterCustomer.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnMasterCustomer.onHoverState.IconLeftImage = null;
            this.BtnMasterCustomer.onHoverState.IconRightImage = null;
            this.BtnMasterCustomer.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.BtnMasterCustomer.OnIdleState.BorderRadius = 1;
            this.BtnMasterCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnMasterCustomer.OnIdleState.BorderThickness = 1;
            this.BtnMasterCustomer.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.BtnMasterCustomer.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnMasterCustomer.OnIdleState.IconLeftImage = global::WMS.Properties.Resources.client_59694081;
            this.BtnMasterCustomer.OnIdleState.IconRightImage = null;
            this.BtnMasterCustomer.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnMasterCustomer.OnPressedState.BorderRadius = 1;
            this.BtnMasterCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnMasterCustomer.OnPressedState.BorderThickness = 1;
            this.BtnMasterCustomer.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnMasterCustomer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnMasterCustomer.OnPressedState.IconLeftImage = null;
            this.BtnMasterCustomer.OnPressedState.IconRightImage = null;
            this.BtnMasterCustomer.Size = new System.Drawing.Size(257, 45);
            this.BtnMasterCustomer.TabIndex = 12;
            this.BtnMasterCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnMasterCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnMasterCustomer.TextMarginLeft = 0;
            this.BtnMasterCustomer.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.BtnMasterCustomer.UseDefaultRadiusAndThickness = true;
            this.BtnMasterCustomer.Click += new System.EventHandler(this.BtnMasterCustomer_Click);
            // 
            // BtnMasterPart
            // 
            this.BtnMasterPart.AllowAnimations = true;
            this.BtnMasterPart.AllowMouseEffects = true;
            this.BtnMasterPart.AllowToggling = true;
            this.BtnMasterPart.AnimationSpeed = 200;
            this.BtnMasterPart.AutoGenerateColors = false;
            this.BtnMasterPart.AutoRoundBorders = false;
            this.BtnMasterPart.AutoSizeLeftIcon = true;
            this.BtnMasterPart.AutoSizeRightIcon = true;
            this.BtnMasterPart.BackColor = System.Drawing.Color.Transparent;
            this.BtnMasterPart.BackColor1 = System.Drawing.Color.SteelBlue;
            this.BtnMasterPart.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnMasterPart.BackgroundImage")));
            this.BtnMasterPart.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnMasterPart.ButtonText = "Master Part";
            this.BtnMasterPart.ButtonTextMarginLeft = 0;
            this.BtnMasterPart.ColorContrastOnClick = 45;
            this.BtnMasterPart.ColorContrastOnHover = 45;
            this.BtnMasterPart.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BtnMasterPart.CustomizableEdges = borderEdges2;
            this.BtnMasterPart.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnMasterPart.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnMasterPart.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnMasterPart.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnMasterPart.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnMasterPart.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.BtnMasterPart.ForeColor = System.Drawing.Color.White;
            this.BtnMasterPart.IconLeft = global::WMS.Properties.Resources.toolbox_52594921;
            this.BtnMasterPart.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnMasterPart.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnMasterPart.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnMasterPart.IconMarginLeft = 11;
            this.BtnMasterPart.IconPadding = 10;
            this.BtnMasterPart.IconRight = null;
            this.BtnMasterPart.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnMasterPart.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnMasterPart.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnMasterPart.IconSize = 25;
            this.BtnMasterPart.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.BtnMasterPart.IdleBorderRadius = 1;
            this.BtnMasterPart.IdleBorderThickness = 1;
            this.BtnMasterPart.IdleFillColor = System.Drawing.Color.SteelBlue;
            this.BtnMasterPart.IdleIconLeftImage = global::WMS.Properties.Resources.toolbox_52594921;
            this.BtnMasterPart.IdleIconRightImage = null;
            this.BtnMasterPart.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.BtnMasterPart.IndicateFocus = true;
            this.BtnMasterPart.Location = new System.Drawing.Point(0, 469);
            this.BtnMasterPart.Name = "BtnMasterPart";
            this.BtnMasterPart.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnMasterPart.OnDisabledState.BorderRadius = 1;
            this.BtnMasterPart.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnMasterPart.OnDisabledState.BorderThickness = 1;
            this.BtnMasterPart.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnMasterPart.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnMasterPart.OnDisabledState.IconLeftImage = null;
            this.BtnMasterPart.OnDisabledState.IconRightImage = null;
            this.BtnMasterPart.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnMasterPart.onHoverState.BorderRadius = 1;
            this.BtnMasterPart.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnMasterPart.onHoverState.BorderThickness = 1;
            this.BtnMasterPart.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnMasterPart.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnMasterPart.onHoverState.IconLeftImage = null;
            this.BtnMasterPart.onHoverState.IconRightImage = null;
            this.BtnMasterPart.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.BtnMasterPart.OnIdleState.BorderRadius = 1;
            this.BtnMasterPart.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnMasterPart.OnIdleState.BorderThickness = 1;
            this.BtnMasterPart.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.BtnMasterPart.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnMasterPart.OnIdleState.IconLeftImage = global::WMS.Properties.Resources.toolbox_52594921;
            this.BtnMasterPart.OnIdleState.IconRightImage = null;
            this.BtnMasterPart.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnMasterPart.OnPressedState.BorderRadius = 1;
            this.BtnMasterPart.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnMasterPart.OnPressedState.BorderThickness = 1;
            this.BtnMasterPart.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnMasterPart.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnMasterPart.OnPressedState.IconLeftImage = null;
            this.BtnMasterPart.OnPressedState.IconRightImage = null;
            this.BtnMasterPart.Size = new System.Drawing.Size(254, 45);
            this.BtnMasterPart.TabIndex = 11;
            this.BtnMasterPart.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnMasterPart.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnMasterPart.TextMarginLeft = 0;
            this.BtnMasterPart.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.BtnMasterPart.UseDefaultRadiusAndThickness = true;
            this.BtnMasterPart.Click += new System.EventHandler(this.BtnMasterPart_Click);
            // 
            // BtnRackLocation
            // 
            this.BtnRackLocation.AllowAnimations = true;
            this.BtnRackLocation.AllowMouseEffects = true;
            this.BtnRackLocation.AllowToggling = true;
            this.BtnRackLocation.AnimationSpeed = 200;
            this.BtnRackLocation.AutoGenerateColors = false;
            this.BtnRackLocation.AutoRoundBorders = false;
            this.BtnRackLocation.AutoSizeLeftIcon = true;
            this.BtnRackLocation.AutoSizeRightIcon = true;
            this.BtnRackLocation.BackColor = System.Drawing.Color.Transparent;
            this.BtnRackLocation.BackColor1 = System.Drawing.Color.SteelBlue;
            this.BtnRackLocation.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnRackLocation.BackgroundImage")));
            this.BtnRackLocation.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnRackLocation.ButtonText = "Rack Location";
            this.BtnRackLocation.ButtonTextMarginLeft = 0;
            this.BtnRackLocation.ColorContrastOnClick = 45;
            this.BtnRackLocation.ColorContrastOnHover = 45;
            this.BtnRackLocation.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnRackLocation.CustomizableEdges = borderEdges3;
            this.BtnRackLocation.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnRackLocation.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnRackLocation.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnRackLocation.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnRackLocation.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnRackLocation.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.BtnRackLocation.ForeColor = System.Drawing.Color.White;
            this.BtnRackLocation.IconLeft = global::WMS.Properties.Resources.searchbox1;
            this.BtnRackLocation.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnRackLocation.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnRackLocation.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnRackLocation.IconMarginLeft = 11;
            this.BtnRackLocation.IconPadding = 10;
            this.BtnRackLocation.IconRight = null;
            this.BtnRackLocation.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnRackLocation.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnRackLocation.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnRackLocation.IconSize = 25;
            this.BtnRackLocation.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.BtnRackLocation.IdleBorderRadius = 1;
            this.BtnRackLocation.IdleBorderThickness = 1;
            this.BtnRackLocation.IdleFillColor = System.Drawing.Color.SteelBlue;
            this.BtnRackLocation.IdleIconLeftImage = global::WMS.Properties.Resources.searchbox1;
            this.BtnRackLocation.IdleIconRightImage = null;
            this.BtnRackLocation.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.BtnRackLocation.IndicateFocus = true;
            this.BtnRackLocation.Location = new System.Drawing.Point(1, 418);
            this.BtnRackLocation.Name = "BtnRackLocation";
            this.BtnRackLocation.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnRackLocation.OnDisabledState.BorderRadius = 1;
            this.BtnRackLocation.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnRackLocation.OnDisabledState.BorderThickness = 1;
            this.BtnRackLocation.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnRackLocation.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnRackLocation.OnDisabledState.IconLeftImage = null;
            this.BtnRackLocation.OnDisabledState.IconRightImage = null;
            this.BtnRackLocation.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnRackLocation.onHoverState.BorderRadius = 1;
            this.BtnRackLocation.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnRackLocation.onHoverState.BorderThickness = 1;
            this.BtnRackLocation.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnRackLocation.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnRackLocation.onHoverState.IconLeftImage = null;
            this.BtnRackLocation.onHoverState.IconRightImage = null;
            this.BtnRackLocation.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.BtnRackLocation.OnIdleState.BorderRadius = 1;
            this.BtnRackLocation.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnRackLocation.OnIdleState.BorderThickness = 1;
            this.BtnRackLocation.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.BtnRackLocation.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnRackLocation.OnIdleState.IconLeftImage = global::WMS.Properties.Resources.searchbox1;
            this.BtnRackLocation.OnIdleState.IconRightImage = null;
            this.BtnRackLocation.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnRackLocation.OnPressedState.BorderRadius = 1;
            this.BtnRackLocation.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnRackLocation.OnPressedState.BorderThickness = 1;
            this.BtnRackLocation.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnRackLocation.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnRackLocation.OnPressedState.IconLeftImage = null;
            this.BtnRackLocation.OnPressedState.IconRightImage = null;
            this.BtnRackLocation.Size = new System.Drawing.Size(254, 45);
            this.BtnRackLocation.TabIndex = 10;
            this.BtnRackLocation.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnRackLocation.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnRackLocation.TextMarginLeft = 0;
            this.BtnRackLocation.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.BtnRackLocation.UseDefaultRadiusAndThickness = true;
            this.BtnRackLocation.Click += new System.EventHandler(this.BtnRackLocation_Click);
            // 
            // BtnSetting
            // 
            this.BtnSetting.AllowAnimations = true;
            this.BtnSetting.AllowMouseEffects = true;
            this.BtnSetting.AllowToggling = true;
            this.BtnSetting.AnimationSpeed = 200;
            this.BtnSetting.AutoGenerateColors = false;
            this.BtnSetting.AutoRoundBorders = false;
            this.BtnSetting.AutoSizeLeftIcon = true;
            this.BtnSetting.AutoSizeRightIcon = true;
            this.BtnSetting.BackColor = System.Drawing.Color.Transparent;
            this.BtnSetting.BackColor1 = System.Drawing.Color.SteelBlue;
            this.BtnSetting.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnSetting.BackgroundImage")));
            this.BtnSetting.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSetting.ButtonText = "Setting";
            this.BtnSetting.ButtonTextMarginLeft = 0;
            this.BtnSetting.ColorContrastOnClick = 45;
            this.BtnSetting.ColorContrastOnHover = 45;
            this.BtnSetting.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BtnSetting.CustomizableEdges = borderEdges4;
            this.BtnSetting.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnSetting.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnSetting.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnSetting.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnSetting.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnSetting.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.BtnSetting.ForeColor = System.Drawing.Color.White;
            this.BtnSetting.IconLeft = global::WMS.Properties.Resources.settings_1_1;
            this.BtnSetting.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnSetting.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnSetting.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnSetting.IconMarginLeft = 11;
            this.BtnSetting.IconPadding = 10;
            this.BtnSetting.IconRight = null;
            this.BtnSetting.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnSetting.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnSetting.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnSetting.IconSize = 25;
            this.BtnSetting.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.BtnSetting.IdleBorderRadius = 1;
            this.BtnSetting.IdleBorderThickness = 1;
            this.BtnSetting.IdleFillColor = System.Drawing.Color.SteelBlue;
            this.BtnSetting.IdleIconLeftImage = global::WMS.Properties.Resources.settings_1_1;
            this.BtnSetting.IdleIconRightImage = null;
            this.BtnSetting.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.BtnSetting.IndicateFocus = true;
            this.BtnSetting.Location = new System.Drawing.Point(0, 674);
            this.BtnSetting.Name = "BtnSetting";
            this.BtnSetting.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnSetting.OnDisabledState.BorderRadius = 1;
            this.BtnSetting.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSetting.OnDisabledState.BorderThickness = 1;
            this.BtnSetting.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnSetting.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnSetting.OnDisabledState.IconLeftImage = null;
            this.BtnSetting.OnDisabledState.IconRightImage = null;
            this.BtnSetting.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnSetting.onHoverState.BorderRadius = 1;
            this.BtnSetting.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSetting.onHoverState.BorderThickness = 1;
            this.BtnSetting.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnSetting.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnSetting.onHoverState.IconLeftImage = null;
            this.BtnSetting.onHoverState.IconRightImage = null;
            this.BtnSetting.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.BtnSetting.OnIdleState.BorderRadius = 1;
            this.BtnSetting.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSetting.OnIdleState.BorderThickness = 1;
            this.BtnSetting.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.BtnSetting.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnSetting.OnIdleState.IconLeftImage = global::WMS.Properties.Resources.settings_1_1;
            this.BtnSetting.OnIdleState.IconRightImage = null;
            this.BtnSetting.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnSetting.OnPressedState.BorderRadius = 1;
            this.BtnSetting.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSetting.OnPressedState.BorderThickness = 1;
            this.BtnSetting.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnSetting.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnSetting.OnPressedState.IconLeftImage = null;
            this.BtnSetting.OnPressedState.IconRightImage = null;
            this.BtnSetting.Size = new System.Drawing.Size(254, 45);
            this.BtnSetting.TabIndex = 9;
            this.BtnSetting.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnSetting.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnSetting.TextMarginLeft = 0;
            this.BtnSetting.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.BtnSetting.UseDefaultRadiusAndThickness = true;
            this.BtnSetting.Click += new System.EventHandler(this.BtnSetting_Click);
            // 
            // BtnLogHistory
            // 
            this.BtnLogHistory.AllowAnimations = true;
            this.BtnLogHistory.AllowMouseEffects = true;
            this.BtnLogHistory.AllowToggling = true;
            this.BtnLogHistory.AnimationSpeed = 200;
            this.BtnLogHistory.AutoGenerateColors = false;
            this.BtnLogHistory.AutoRoundBorders = false;
            this.BtnLogHistory.AutoSizeLeftIcon = true;
            this.BtnLogHistory.AutoSizeRightIcon = true;
            this.BtnLogHistory.BackColor = System.Drawing.Color.Transparent;
            this.BtnLogHistory.BackColor1 = System.Drawing.Color.SteelBlue;
            this.BtnLogHistory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnLogHistory.BackgroundImage")));
            this.BtnLogHistory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLogHistory.ButtonText = "Log History";
            this.BtnLogHistory.ButtonTextMarginLeft = 0;
            this.BtnLogHistory.ColorContrastOnClick = 45;
            this.BtnLogHistory.ColorContrastOnHover = 45;
            this.BtnLogHistory.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.BtnLogHistory.CustomizableEdges = borderEdges5;
            this.BtnLogHistory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnLogHistory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnLogHistory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnLogHistory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnLogHistory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnLogHistory.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.BtnLogHistory.ForeColor = System.Drawing.Color.White;
            this.BtnLogHistory.IconLeft = global::WMS.Properties.Resources.log1;
            this.BtnLogHistory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnLogHistory.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnLogHistory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnLogHistory.IconMarginLeft = 11;
            this.BtnLogHistory.IconPadding = 10;
            this.BtnLogHistory.IconRight = null;
            this.BtnLogHistory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnLogHistory.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnLogHistory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnLogHistory.IconSize = 25;
            this.BtnLogHistory.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.BtnLogHistory.IdleBorderRadius = 1;
            this.BtnLogHistory.IdleBorderThickness = 1;
            this.BtnLogHistory.IdleFillColor = System.Drawing.Color.SteelBlue;
            this.BtnLogHistory.IdleIconLeftImage = global::WMS.Properties.Resources.log1;
            this.BtnLogHistory.IdleIconRightImage = null;
            this.BtnLogHistory.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.BtnLogHistory.IndicateFocus = true;
            this.BtnLogHistory.Location = new System.Drawing.Point(-1, 623);
            this.BtnLogHistory.Name = "BtnLogHistory";
            this.BtnLogHistory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnLogHistory.OnDisabledState.BorderRadius = 1;
            this.BtnLogHistory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLogHistory.OnDisabledState.BorderThickness = 1;
            this.BtnLogHistory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnLogHistory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnLogHistory.OnDisabledState.IconLeftImage = null;
            this.BtnLogHistory.OnDisabledState.IconRightImage = null;
            this.BtnLogHistory.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnLogHistory.onHoverState.BorderRadius = 1;
            this.BtnLogHistory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLogHistory.onHoverState.BorderThickness = 1;
            this.BtnLogHistory.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnLogHistory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnLogHistory.onHoverState.IconLeftImage = null;
            this.BtnLogHistory.onHoverState.IconRightImage = null;
            this.BtnLogHistory.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.BtnLogHistory.OnIdleState.BorderRadius = 1;
            this.BtnLogHistory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLogHistory.OnIdleState.BorderThickness = 1;
            this.BtnLogHistory.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.BtnLogHistory.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnLogHistory.OnIdleState.IconLeftImage = global::WMS.Properties.Resources.log1;
            this.BtnLogHistory.OnIdleState.IconRightImage = null;
            this.BtnLogHistory.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnLogHistory.OnPressedState.BorderRadius = 1;
            this.BtnLogHistory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLogHistory.OnPressedState.BorderThickness = 1;
            this.BtnLogHistory.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnLogHistory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnLogHistory.OnPressedState.IconLeftImage = null;
            this.BtnLogHistory.OnPressedState.IconRightImage = null;
            this.BtnLogHistory.Size = new System.Drawing.Size(254, 45);
            this.BtnLogHistory.TabIndex = 8;
            this.BtnLogHistory.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnLogHistory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnLogHistory.TextMarginLeft = 0;
            this.BtnLogHistory.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.BtnLogHistory.UseDefaultRadiusAndThickness = true;
            this.BtnLogHistory.Click += new System.EventHandler(this.BtnLogHistory_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Location = new System.Drawing.Point(15, 37);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(227, 86);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 7;
            this.pictureBox1.TabStop = false;
            // 
            // BtnUser
            // 
            this.BtnUser.AllowAnimations = true;
            this.BtnUser.AllowMouseEffects = true;
            this.BtnUser.AllowToggling = true;
            this.BtnUser.AnimationSpeed = 200;
            this.BtnUser.AutoGenerateColors = false;
            this.BtnUser.AutoRoundBorders = false;
            this.BtnUser.AutoSizeLeftIcon = true;
            this.BtnUser.AutoSizeRightIcon = true;
            this.BtnUser.BackColor = System.Drawing.Color.Transparent;
            this.BtnUser.BackColor1 = System.Drawing.Color.SteelBlue;
            this.BtnUser.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnUser.BackgroundImage")));
            this.BtnUser.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUser.ButtonText = "User";
            this.BtnUser.ButtonTextMarginLeft = 0;
            this.BtnUser.ColorContrastOnClick = 45;
            this.BtnUser.ColorContrastOnHover = 45;
            this.BtnUser.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.BtnUser.CustomizableEdges = borderEdges6;
            this.BtnUser.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnUser.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUser.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnUser.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnUser.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnUser.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.BtnUser.ForeColor = System.Drawing.Color.White;
            this.BtnUser.IconLeft = global::WMS.Properties.Resources.user1;
            this.BtnUser.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnUser.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUser.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnUser.IconMarginLeft = 11;
            this.BtnUser.IconPadding = 10;
            this.BtnUser.IconRight = null;
            this.BtnUser.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnUser.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUser.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnUser.IconSize = 25;
            this.BtnUser.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.BtnUser.IdleBorderRadius = 1;
            this.BtnUser.IdleBorderThickness = 1;
            this.BtnUser.IdleFillColor = System.Drawing.Color.SteelBlue;
            this.BtnUser.IdleIconLeftImage = global::WMS.Properties.Resources.user1;
            this.BtnUser.IdleIconRightImage = null;
            this.BtnUser.IndicateFocus = true;
            this.BtnUser.Location = new System.Drawing.Point(2, 572);
            this.BtnUser.Name = "BtnUser";
            this.BtnUser.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUser.OnDisabledState.BorderRadius = 1;
            this.BtnUser.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUser.OnDisabledState.BorderThickness = 1;
            this.BtnUser.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnUser.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnUser.OnDisabledState.IconLeftImage = null;
            this.BtnUser.OnDisabledState.IconRightImage = null;
            this.BtnUser.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnUser.onHoverState.BorderRadius = 1;
            this.BtnUser.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUser.onHoverState.BorderThickness = 1;
            this.BtnUser.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnUser.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnUser.onHoverState.IconLeftImage = null;
            this.BtnUser.onHoverState.IconRightImage = null;
            this.BtnUser.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.BtnUser.OnIdleState.BorderRadius = 1;
            this.BtnUser.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUser.OnIdleState.BorderThickness = 1;
            this.BtnUser.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.BtnUser.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnUser.OnIdleState.IconLeftImage = global::WMS.Properties.Resources.user1;
            this.BtnUser.OnIdleState.IconRightImage = null;
            this.BtnUser.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnUser.OnPressedState.BorderRadius = 1;
            this.BtnUser.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUser.OnPressedState.BorderThickness = 1;
            this.BtnUser.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnUser.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnUser.OnPressedState.IconLeftImage = null;
            this.BtnUser.OnPressedState.IconRightImage = null;
            this.BtnUser.Size = new System.Drawing.Size(252, 45);
            this.BtnUser.TabIndex = 4;
            this.BtnUser.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnUser.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnUser.TextMarginLeft = 0;
            this.BtnUser.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.BtnUser.UseDefaultRadiusAndThickness = true;
            this.BtnUser.Click += new System.EventHandler(this.BtnUser_Click);
            // 
            // BtnBalance
            // 
            this.BtnBalance.AllowAnimations = true;
            this.BtnBalance.AllowMouseEffects = true;
            this.BtnBalance.AllowToggling = true;
            this.BtnBalance.AnimationSpeed = 200;
            this.BtnBalance.AutoGenerateColors = false;
            this.BtnBalance.AutoRoundBorders = false;
            this.BtnBalance.AutoSizeLeftIcon = true;
            this.BtnBalance.AutoSizeRightIcon = true;
            this.BtnBalance.BackColor = System.Drawing.Color.Transparent;
            this.BtnBalance.BackColor1 = System.Drawing.Color.SteelBlue;
            this.BtnBalance.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnBalance.BackgroundImage")));
            this.BtnBalance.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnBalance.ButtonText = "Balance";
            this.BtnBalance.ButtonTextMarginLeft = 0;
            this.BtnBalance.ColorContrastOnClick = 45;
            this.BtnBalance.ColorContrastOnHover = 45;
            this.BtnBalance.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.BtnBalance.CustomizableEdges = borderEdges7;
            this.BtnBalance.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnBalance.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnBalance.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnBalance.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnBalance.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnBalance.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.BtnBalance.ForeColor = System.Drawing.Color.White;
            this.BtnBalance.IconLeft = global::WMS.Properties.Resources.box1;
            this.BtnBalance.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnBalance.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnBalance.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnBalance.IconMarginLeft = 11;
            this.BtnBalance.IconPadding = 10;
            this.BtnBalance.IconRight = null;
            this.BtnBalance.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnBalance.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnBalance.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnBalance.IconSize = 25;
            this.BtnBalance.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.BtnBalance.IdleBorderRadius = 1;
            this.BtnBalance.IdleBorderThickness = 1;
            this.BtnBalance.IdleFillColor = System.Drawing.Color.SteelBlue;
            this.BtnBalance.IdleIconLeftImage = global::WMS.Properties.Resources.box1;
            this.BtnBalance.IdleIconRightImage = null;
            this.BtnBalance.IndicateFocus = true;
            this.BtnBalance.Location = new System.Drawing.Point(0, 367);
            this.BtnBalance.Name = "BtnBalance";
            this.BtnBalance.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnBalance.OnDisabledState.BorderRadius = 1;
            this.BtnBalance.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnBalance.OnDisabledState.BorderThickness = 1;
            this.BtnBalance.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnBalance.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnBalance.OnDisabledState.IconLeftImage = null;
            this.BtnBalance.OnDisabledState.IconRightImage = null;
            this.BtnBalance.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnBalance.onHoverState.BorderRadius = 1;
            this.BtnBalance.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnBalance.onHoverState.BorderThickness = 1;
            this.BtnBalance.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnBalance.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnBalance.onHoverState.IconLeftImage = null;
            this.BtnBalance.onHoverState.IconRightImage = null;
            this.BtnBalance.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.BtnBalance.OnIdleState.BorderRadius = 1;
            this.BtnBalance.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnBalance.OnIdleState.BorderThickness = 1;
            this.BtnBalance.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.BtnBalance.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnBalance.OnIdleState.IconLeftImage = global::WMS.Properties.Resources.box1;
            this.BtnBalance.OnIdleState.IconRightImage = null;
            this.BtnBalance.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnBalance.OnPressedState.BorderRadius = 1;
            this.BtnBalance.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnBalance.OnPressedState.BorderThickness = 1;
            this.BtnBalance.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnBalance.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnBalance.OnPressedState.IconLeftImage = null;
            this.BtnBalance.OnPressedState.IconRightImage = null;
            this.BtnBalance.Size = new System.Drawing.Size(255, 45);
            this.BtnBalance.TabIndex = 3;
            this.BtnBalance.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnBalance.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnBalance.TextMarginLeft = 0;
            this.BtnBalance.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.BtnBalance.UseDefaultRadiusAndThickness = true;
            this.BtnBalance.Click += new System.EventHandler(this.BtnBalance_Click);
            // 
            // BtnStockOut
            // 
            this.BtnStockOut.AllowAnimations = true;
            this.BtnStockOut.AllowMouseEffects = true;
            this.BtnStockOut.AllowToggling = true;
            this.BtnStockOut.AnimationSpeed = 200;
            this.BtnStockOut.AutoGenerateColors = false;
            this.BtnStockOut.AutoRoundBorders = false;
            this.BtnStockOut.AutoSizeLeftIcon = true;
            this.BtnStockOut.AutoSizeRightIcon = true;
            this.BtnStockOut.BackColor = System.Drawing.Color.Transparent;
            this.BtnStockOut.BackColor1 = System.Drawing.Color.SteelBlue;
            this.BtnStockOut.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnStockOut.BackgroundImage")));
            this.BtnStockOut.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnStockOut.ButtonText = "Stock Out";
            this.BtnStockOut.ButtonTextMarginLeft = 0;
            this.BtnStockOut.ColorContrastOnClick = 45;
            this.BtnStockOut.ColorContrastOnHover = 45;
            this.BtnStockOut.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.BtnStockOut.CustomizableEdges = borderEdges8;
            this.BtnStockOut.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnStockOut.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnStockOut.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnStockOut.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnStockOut.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnStockOut.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.BtnStockOut.ForeColor = System.Drawing.Color.White;
            this.BtnStockOut.IconLeft = global::WMS.Properties.Resources.delivery_truck1;
            this.BtnStockOut.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnStockOut.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnStockOut.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnStockOut.IconMarginLeft = 11;
            this.BtnStockOut.IconPadding = 10;
            this.BtnStockOut.IconRight = null;
            this.BtnStockOut.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnStockOut.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnStockOut.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnStockOut.IconSize = 25;
            this.BtnStockOut.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.BtnStockOut.IdleBorderRadius = 1;
            this.BtnStockOut.IdleBorderThickness = 1;
            this.BtnStockOut.IdleFillColor = System.Drawing.Color.SteelBlue;
            this.BtnStockOut.IdleIconLeftImage = global::WMS.Properties.Resources.delivery_truck1;
            this.BtnStockOut.IdleIconRightImage = null;
            this.BtnStockOut.IndicateFocus = true;
            this.BtnStockOut.Location = new System.Drawing.Point(0, 316);
            this.BtnStockOut.Name = "BtnStockOut";
            this.BtnStockOut.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnStockOut.OnDisabledState.BorderRadius = 1;
            this.BtnStockOut.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnStockOut.OnDisabledState.BorderThickness = 1;
            this.BtnStockOut.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnStockOut.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnStockOut.OnDisabledState.IconLeftImage = null;
            this.BtnStockOut.OnDisabledState.IconRightImage = null;
            this.BtnStockOut.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnStockOut.onHoverState.BorderRadius = 1;
            this.BtnStockOut.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnStockOut.onHoverState.BorderThickness = 1;
            this.BtnStockOut.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnStockOut.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnStockOut.onHoverState.IconLeftImage = null;
            this.BtnStockOut.onHoverState.IconRightImage = null;
            this.BtnStockOut.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.BtnStockOut.OnIdleState.BorderRadius = 1;
            this.BtnStockOut.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnStockOut.OnIdleState.BorderThickness = 1;
            this.BtnStockOut.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.BtnStockOut.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnStockOut.OnIdleState.IconLeftImage = global::WMS.Properties.Resources.delivery_truck1;
            this.BtnStockOut.OnIdleState.IconRightImage = null;
            this.BtnStockOut.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnStockOut.OnPressedState.BorderRadius = 1;
            this.BtnStockOut.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnStockOut.OnPressedState.BorderThickness = 1;
            this.BtnStockOut.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnStockOut.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnStockOut.OnPressedState.IconLeftImage = null;
            this.BtnStockOut.OnPressedState.IconRightImage = null;
            this.BtnStockOut.Size = new System.Drawing.Size(254, 45);
            this.BtnStockOut.TabIndex = 2;
            this.BtnStockOut.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnStockOut.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnStockOut.TextMarginLeft = 0;
            this.BtnStockOut.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.BtnStockOut.UseDefaultRadiusAndThickness = true;
            this.BtnStockOut.Click += new System.EventHandler(this.BtnStockOut_Click);
            // 
            // BtnGenerate
            // 
            this.BtnGenerate.AllowAnimations = true;
            this.BtnGenerate.AllowMouseEffects = true;
            this.BtnGenerate.AllowToggling = true;
            this.BtnGenerate.AnimationSpeed = 200;
            this.BtnGenerate.AutoGenerateColors = false;
            this.BtnGenerate.AutoRoundBorders = false;
            this.BtnGenerate.AutoSizeLeftIcon = true;
            this.BtnGenerate.AutoSizeRightIcon = true;
            this.BtnGenerate.BackColor = System.Drawing.Color.Transparent;
            this.BtnGenerate.BackColor1 = System.Drawing.Color.SteelBlue;
            this.BtnGenerate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnGenerate.BackgroundImage")));
            this.BtnGenerate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGenerate.ButtonText = "Generate QR";
            this.BtnGenerate.ButtonTextMarginLeft = 0;
            this.BtnGenerate.ColorContrastOnClick = 45;
            this.BtnGenerate.ColorContrastOnHover = 45;
            this.BtnGenerate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.BtnGenerate.CustomizableEdges = borderEdges9;
            this.BtnGenerate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnGenerate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnGenerate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnGenerate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnGenerate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnGenerate.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.BtnGenerate.ForeColor = System.Drawing.Color.White;
            this.BtnGenerate.IconLeft = global::WMS.Properties.Resources.qr;
            this.BtnGenerate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnGenerate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnGenerate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnGenerate.IconMarginLeft = 11;
            this.BtnGenerate.IconPadding = 10;
            this.BtnGenerate.IconRight = null;
            this.BtnGenerate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnGenerate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnGenerate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnGenerate.IconSize = 25;
            this.BtnGenerate.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.BtnGenerate.IdleBorderRadius = 1;
            this.BtnGenerate.IdleBorderThickness = 1;
            this.BtnGenerate.IdleFillColor = System.Drawing.Color.SteelBlue;
            this.BtnGenerate.IdleIconLeftImage = global::WMS.Properties.Resources.qr;
            this.BtnGenerate.IdleIconRightImage = null;
            this.BtnGenerate.IndicateFocus = true;
            this.BtnGenerate.Location = new System.Drawing.Point(3, 214);
            this.BtnGenerate.Name = "BtnGenerate";
            this.BtnGenerate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnGenerate.OnDisabledState.BorderRadius = 1;
            this.BtnGenerate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGenerate.OnDisabledState.BorderThickness = 1;
            this.BtnGenerate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnGenerate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnGenerate.OnDisabledState.IconLeftImage = null;
            this.BtnGenerate.OnDisabledState.IconRightImage = null;
            this.BtnGenerate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnGenerate.onHoverState.BorderRadius = 1;
            this.BtnGenerate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGenerate.onHoverState.BorderThickness = 1;
            this.BtnGenerate.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnGenerate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnGenerate.onHoverState.IconLeftImage = null;
            this.BtnGenerate.onHoverState.IconRightImage = null;
            this.BtnGenerate.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.BtnGenerate.OnIdleState.BorderRadius = 1;
            this.BtnGenerate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGenerate.OnIdleState.BorderThickness = 1;
            this.BtnGenerate.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.BtnGenerate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnGenerate.OnIdleState.IconLeftImage = global::WMS.Properties.Resources.qr;
            this.BtnGenerate.OnIdleState.IconRightImage = null;
            this.BtnGenerate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnGenerate.OnPressedState.BorderRadius = 1;
            this.BtnGenerate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGenerate.OnPressedState.BorderThickness = 1;
            this.BtnGenerate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnGenerate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnGenerate.OnPressedState.IconLeftImage = null;
            this.BtnGenerate.OnPressedState.IconRightImage = null;
            this.BtnGenerate.Size = new System.Drawing.Size(254, 45);
            this.BtnGenerate.TabIndex = 1;
            this.BtnGenerate.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnGenerate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnGenerate.TextMarginLeft = 0;
            this.BtnGenerate.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.BtnGenerate.UseDefaultRadiusAndThickness = true;
            this.BtnGenerate.Click += new System.EventHandler(this.BtnGenerate_Click);
            // 
            // BtnStockIn
            // 
            this.BtnStockIn.AllowAnimations = true;
            this.BtnStockIn.AllowMouseEffects = true;
            this.BtnStockIn.AllowToggling = true;
            this.BtnStockIn.AnimationSpeed = 200;
            this.BtnStockIn.AutoGenerateColors = false;
            this.BtnStockIn.AutoRoundBorders = false;
            this.BtnStockIn.AutoSizeLeftIcon = true;
            this.BtnStockIn.AutoSizeRightIcon = true;
            this.BtnStockIn.BackColor = System.Drawing.Color.Transparent;
            this.BtnStockIn.BackColor1 = System.Drawing.Color.SteelBlue;
            this.BtnStockIn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnStockIn.BackgroundImage")));
            this.BtnStockIn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnStockIn.ButtonText = "Stock In";
            this.BtnStockIn.ButtonTextMarginLeft = 0;
            this.BtnStockIn.ColorContrastOnClick = 45;
            this.BtnStockIn.ColorContrastOnHover = 45;
            this.BtnStockIn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.BtnStockIn.CustomizableEdges = borderEdges10;
            this.BtnStockIn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnStockIn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnStockIn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnStockIn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnStockIn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnStockIn.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.BtnStockIn.ForeColor = System.Drawing.Color.White;
            this.BtnStockIn.IconLeft = global::WMS.Properties.Resources.pallet;
            this.BtnStockIn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnStockIn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnStockIn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnStockIn.IconMarginLeft = 11;
            this.BtnStockIn.IconPadding = 10;
            this.BtnStockIn.IconRight = null;
            this.BtnStockIn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnStockIn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnStockIn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnStockIn.IconSize = 25;
            this.BtnStockIn.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.BtnStockIn.IdleBorderRadius = 1;
            this.BtnStockIn.IdleBorderThickness = 1;
            this.BtnStockIn.IdleFillColor = System.Drawing.Color.SteelBlue;
            this.BtnStockIn.IdleIconLeftImage = global::WMS.Properties.Resources.pallet;
            this.BtnStockIn.IdleIconRightImage = null;
            this.BtnStockIn.IndicateFocus = true;
            this.BtnStockIn.Location = new System.Drawing.Point(0, 265);
            this.BtnStockIn.Name = "BtnStockIn";
            this.BtnStockIn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnStockIn.OnDisabledState.BorderRadius = 1;
            this.BtnStockIn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnStockIn.OnDisabledState.BorderThickness = 1;
            this.BtnStockIn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnStockIn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnStockIn.OnDisabledState.IconLeftImage = null;
            this.BtnStockIn.OnDisabledState.IconRightImage = null;
            this.BtnStockIn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnStockIn.onHoverState.BorderRadius = 1;
            this.BtnStockIn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnStockIn.onHoverState.BorderThickness = 1;
            this.BtnStockIn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnStockIn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnStockIn.onHoverState.IconLeftImage = null;
            this.BtnStockIn.onHoverState.IconRightImage = null;
            this.BtnStockIn.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.BtnStockIn.OnIdleState.BorderRadius = 1;
            this.BtnStockIn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnStockIn.OnIdleState.BorderThickness = 1;
            this.BtnStockIn.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.BtnStockIn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnStockIn.OnIdleState.IconLeftImage = global::WMS.Properties.Resources.pallet;
            this.BtnStockIn.OnIdleState.IconRightImage = null;
            this.BtnStockIn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnStockIn.OnPressedState.BorderRadius = 1;
            this.BtnStockIn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnStockIn.OnPressedState.BorderThickness = 1;
            this.BtnStockIn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnStockIn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnStockIn.OnPressedState.IconLeftImage = null;
            this.BtnStockIn.OnPressedState.IconRightImage = null;
            this.BtnStockIn.Size = new System.Drawing.Size(257, 45);
            this.BtnStockIn.TabIndex = 1;
            this.BtnStockIn.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnStockIn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnStockIn.TextMarginLeft = 0;
            this.BtnStockIn.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.BtnStockIn.UseDefaultRadiusAndThickness = true;
            this.BtnStockIn.Click += new System.EventHandler(this.BtnStockIn_Click);
            // 
            // BtnSystemOverview
            // 
            this.BtnSystemOverview.AllowAnimations = true;
            this.BtnSystemOverview.AllowMouseEffects = true;
            this.BtnSystemOverview.AllowToggling = false;
            this.BtnSystemOverview.AnimationSpeed = 200;
            this.BtnSystemOverview.AutoGenerateColors = false;
            this.BtnSystemOverview.AutoRoundBorders = false;
            this.BtnSystemOverview.AutoSizeLeftIcon = true;
            this.BtnSystemOverview.AutoSizeRightIcon = true;
            this.BtnSystemOverview.BackColor = System.Drawing.Color.Transparent;
            this.BtnSystemOverview.BackColor1 = System.Drawing.Color.SteelBlue;
            this.BtnSystemOverview.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnSystemOverview.BackgroundImage")));
            this.BtnSystemOverview.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSystemOverview.ButtonText = "System Overview";
            this.BtnSystemOverview.ButtonTextMarginLeft = 0;
            this.BtnSystemOverview.ColorContrastOnClick = 45;
            this.BtnSystemOverview.ColorContrastOnHover = 45;
            this.BtnSystemOverview.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.BtnSystemOverview.CustomizableEdges = borderEdges11;
            this.BtnSystemOverview.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnSystemOverview.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnSystemOverview.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnSystemOverview.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnSystemOverview.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnSystemOverview.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.BtnSystemOverview.ForeColor = System.Drawing.Color.White;
            this.BtnSystemOverview.IconLeft = global::WMS.Properties.Resources.house;
            this.BtnSystemOverview.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnSystemOverview.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnSystemOverview.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnSystemOverview.IconMarginLeft = 11;
            this.BtnSystemOverview.IconPadding = 10;
            this.BtnSystemOverview.IconRight = null;
            this.BtnSystemOverview.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnSystemOverview.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnSystemOverview.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnSystemOverview.IconSize = 25;
            this.BtnSystemOverview.IdleBorderColor = System.Drawing.Color.SteelBlue;
            this.BtnSystemOverview.IdleBorderRadius = 1;
            this.BtnSystemOverview.IdleBorderThickness = 1;
            this.BtnSystemOverview.IdleFillColor = System.Drawing.Color.SteelBlue;
            this.BtnSystemOverview.IdleIconLeftImage = global::WMS.Properties.Resources.house;
            this.BtnSystemOverview.IdleIconRightImage = null;
            this.BtnSystemOverview.IndicateFocus = true;
            this.BtnSystemOverview.Location = new System.Drawing.Point(3, 163);
            this.BtnSystemOverview.Name = "BtnSystemOverview";
            this.BtnSystemOverview.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnSystemOverview.OnDisabledState.BorderRadius = 1;
            this.BtnSystemOverview.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSystemOverview.OnDisabledState.BorderThickness = 1;
            this.BtnSystemOverview.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnSystemOverview.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnSystemOverview.OnDisabledState.IconLeftImage = null;
            this.BtnSystemOverview.OnDisabledState.IconRightImage = null;
            this.BtnSystemOverview.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnSystemOverview.onHoverState.BorderRadius = 1;
            this.BtnSystemOverview.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSystemOverview.onHoverState.BorderThickness = 1;
            this.BtnSystemOverview.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnSystemOverview.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnSystemOverview.onHoverState.IconLeftImage = null;
            this.BtnSystemOverview.onHoverState.IconRightImage = null;
            this.BtnSystemOverview.OnIdleState.BorderColor = System.Drawing.Color.SteelBlue;
            this.BtnSystemOverview.OnIdleState.BorderRadius = 1;
            this.BtnSystemOverview.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSystemOverview.OnIdleState.BorderThickness = 1;
            this.BtnSystemOverview.OnIdleState.FillColor = System.Drawing.Color.SteelBlue;
            this.BtnSystemOverview.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnSystemOverview.OnIdleState.IconLeftImage = global::WMS.Properties.Resources.house;
            this.BtnSystemOverview.OnIdleState.IconRightImage = null;
            this.BtnSystemOverview.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnSystemOverview.OnPressedState.BorderRadius = 1;
            this.BtnSystemOverview.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSystemOverview.OnPressedState.BorderThickness = 1;
            this.BtnSystemOverview.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnSystemOverview.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnSystemOverview.OnPressedState.IconLeftImage = null;
            this.BtnSystemOverview.OnPressedState.IconRightImage = null;
            this.BtnSystemOverview.Size = new System.Drawing.Size(254, 45);
            this.BtnSystemOverview.TabIndex = 0;
            this.BtnSystemOverview.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnSystemOverview.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnSystemOverview.TextMarginLeft = 0;
            this.BtnSystemOverview.TextPadding = new System.Windows.Forms.Padding(60, 0, 0, 0);
            this.BtnSystemOverview.UseDefaultRadiusAndThickness = true;
            this.BtnSystemOverview.Click += new System.EventHandler(this.BtnSystemOverview_Click);
            // 
            // Parent_Panel
            // 
            this.Parent_Panel.BackColor = System.Drawing.SystemColors.GradientInactiveCaption;
            this.Parent_Panel.Controls.Add(this.LblTittle);
            this.Parent_Panel.Controls.Add(this.Main_Panel);
            this.Parent_Panel.Location = new System.Drawing.Point(260, 15);
            this.Parent_Panel.Name = "Parent_Panel";
            this.Parent_Panel.Size = new System.Drawing.Size(1094, 722);
            this.Parent_Panel.TabIndex = 3;
            // 
            // LblTittle
            // 
            this.LblTittle.AllowParentOverrides = false;
            this.LblTittle.AutoEllipsis = false;
            this.LblTittle.AutoSize = false;
            this.LblTittle.CursorType = null;
            this.LblTittle.Font = new System.Drawing.Font("Segoe UI Semibold", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LblTittle.ForeColor = System.Drawing.SystemColors.ActiveCaption;
            this.LblTittle.Location = new System.Drawing.Point(307, 15);
            this.LblTittle.Name = "LblTittle";
            this.LblTittle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LblTittle.Size = new System.Drawing.Size(322, 42);
            this.LblTittle.TabIndex = 6;
            this.LblTittle.Text = "Tittle";
            this.LblTittle.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.LblTittle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Main_Panel
            // 
            this.Main_Panel.BackColor = System.Drawing.SystemColors.ActiveCaption;
            this.Main_Panel.Location = new System.Drawing.Point(39, 72);
            this.Main_Panel.Name = "Main_Panel";
            this.Main_Panel.Size = new System.Drawing.Size(1000, 600);
            this.Main_Panel.TabIndex = 0;
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1370, 749);
            this.Controls.Add(this.sidePanel);
            this.Controls.Add(this.Parent_Panel);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Warehouse Management System";
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.sidePanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.Parent_Panel.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Panel sidePanel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnUser;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnBalance;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnStockOut;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnGenerate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnStockIn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnSystemOverview;
        private System.Windows.Forms.Panel Parent_Panel;
        private Bunifu.UI.WinForms.BunifuLabel LblTittle;
        private System.Windows.Forms.Panel Main_Panel;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnLogHistory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnSetting;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnRackLocation;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnMasterPart;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnMasterCustomer;
    }
}

